### ISSUE TITLE
Can't set attribute in modeling_vqvae

### ISSUE THREAD

**Issue by hxdtest** [PKU-YuanGroup/Open-Sora-Plan#185]
File "opensora/train/train_videogpt.py", line 55, in <module>
    train(args, vqvae_args, training_args)
  File "opensora/train/train_videogpt.py", line 39, in train
    config = VQVAEConfiguration(**asdict(vqvae_args))
  File "/hetero_infer/hanxudong.hxd/Open-Sora-Plan/opensora/models/ae/videobase/vqvae/modeling_vqvae.py", line 718, in __init__
    self.config = config
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1754, in __setattr__
    super().__setattr__(name, value)
AttributeError: can't set attribute
Traceback (most recent call last):
  File "opensora/train/train_videogpt.py", line 55, in <module>
    train(args, vqvae_args, training_args)
  File "opensora/train/train_videogpt.py", line 39, in train
    config = VQVAEConfiguration(**asdict(vqvae_args))
  File "/hetero_infer/hanxudong.hxd/Open-Sora-Plan/opensora/models/ae/videobase/vqvae/modeling_vqvae.py", line 718, in __init__
    self.config = config
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1754, in __setattr__
    super().__setattr__(name, value)
AttributeError: can't set attribute

**Comment by junfengcao** [comment]
> File "opensora/train/train_videogpt.py", line 55, in train(args, vqvae_args, training_args) File "opensora/train/train_videogpt.py", line 39, in train config = VQVAEConfiguration(**asdict(vqvae_args)) File "/hetero_infer/hanxudong.hxd/Open-Sora-Plan/opensora/models/ae/videobase/vqvae/modeling_vqvae.py", line 718, in **init** self.config = config File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1754, in **setattr** super().**setattr**(name, value) AttributeError: can't set attribute Traceback (most recent call last): File "opensora/train/train_videogpt.py", line 55, in train(args, vqvae_args, training_args) File "opensora/train/train_videogpt.py", line 39, in train config = VQVAEConfiguration(**asdict(vqvae_args)) File "/hetero_infer/hanxudong.hxd/Open-Sora-Plan/opensora/models/ae/videobase/vqvae/modeling_vqvae.py", line 718, in **init** self.config = config File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1754, in **setattr** super().**setattr**(name, value) AttributeError: can't set attribute

I met the same question!!

**Comment by PRITIpriy** [comment]
I have the same question @junfengcao
