### ISSUE TITLE
LanguageBind/Open-Sora-Plan-v1.0.0 does not appear to have a file named diffusion_pytorch_model.bin

### ISSUE THREAD

**Issue by momandai** [PKU-YuanGroup/Open-Sora-Plan#202]
CUDA_VISIBLE_DEVICES=0 python opensora/sample/sample_t2v.py     --model_path LanguageBind/Open-Sora-Plan-v1.0.0     --text_encoder_name DeepFloyd/t5-v1_1-xxl     --text_prompt examples/prompt_list_0.txt     --ae CausalVAEModel_4x8x8     --version 65x512x512     --save_img_path "./sample_videos/prompt_list_0"     --fps 24     --guidance_scale 7.5     --num_sampling_steps 250     --enable_tiling
**I ran the above command to generate a sample video, but encountered the following error.**
(opensora-plan) [root@localhost Open-Sora-Plan]# CUDA_VISIBLE_DEVICES=0 python opensora/sample/sample_t2v.py     --model_path LanguageBind/Open-Sora-Plan-v1.0.0     --text_encoder_name DeepFloyd/t5-v1_1-xxl     --text_prompt examples/prompt_list_0.txt     --ae CausalVAEModel_4x8x8     --version 65x512x512     --save_img_path "./sample_videos/prompt_list_0"     --fps 24     --guidance_scale 7.5     --num_sampling_steps 250     --enable_tiling
Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead
Traceback (most recent call last):
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/LanguageBind/Open-Sora-Plan-v1.0.0/resolve/92a849c00ab99ae2c7cd7ff156f2ae02eb25c45d/vae/diffusion_pytorch_model.bin

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/diffusers/utils/hub_utils.py", line 342, in _get_model_file
    model_file = hf_hub_download(
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1261, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1674, in get_hf_file_metadata
    r = _request_wrapper(
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 369, in _request_wrapper
    response = _request_wrapper(
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 393, in _request_wrapper
    hf_raise_for_status(response)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 315, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-661537f5-7d28c5575b3807410f35f16b;634b45ff-5e6d-464a-8767-48488935364d)

Entry Not Found for url: https://huggingface.co/LanguageBind/Open-Sora-Plan-v1.0.0/resolve/92a849c00ab99ae2c7cd7ff156f2ae02eb25c45d/vae/diffusion_pytorch_model.bin.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "opensora/sample/sample_t2v.py", line 161, in <module>
    main(args)
  File "opensora/sample/sample_t2v.py", line 36, in main
    vae = getae_wrapper(args.ae)(args.model_path, subfolder="vae", cache_dir='cache_dir').to(device, dtype=torch.float16)
  File "/home/m00830934/code/Open-Sora-Plan/opensora/models/ae/videobase/causal_vae/__init__.py", line 11, in __init__
    self.vae = CausalVAEModel.from_pretrained(model_path, subfolder=subfolder, cache_dir=cache_dir)
  File "/home/m00830934/code/Open-Sora-Plan/opensora/models/ae/videobase/modeling_videobase.py", line 80, in from_pretrained
    return super().from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 632, in from_pretrained
    model_file = _get_model_file(
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/diffusers/utils/hub_utils.py", line 371, in _get_model_file
    raise EnvironmentError(
OSError: LanguageBind/Open-Sora-Plan-v1.0.0 does not appear to have a file named diffusion_pytorch_model.bin.

**Comment by LinB203** [comment]
It looks like a network connection failure.

**Comment by keno-log** [comment]
got the same "Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead" too. but ran successful.

**Comment by LinB203** [comment]
just warning, ignore it.

> got the same "Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead" too. but ran successful.
