### ISSUE TITLE
causalVAE的训练适配NPU了吗？

### ISSUE THREAD

**Issue by momandai** [PKU-YuanGroup/Open-Sora-Plan#261]
我尝试用npu训练causalVAE，出现如下报错：
Building datasets...
/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/torch_npu/npu/utils.py:88: UserWarning: torch.npu.get_device_capability isn't implemented!
  warnings.warn("torch.npu.get_device_capability isn't implemented!")
Traceback (most recent call last):
  File "/home/m00830934/code/Open-Sora-Plan/opensora/train/train_causalvae.py", line 108, in <module>
    train(args[0])
  File "/home/m00830934/code/Open-Sora-Plan/opensora/train/train_causalvae.py", line 97, in train
    trainer.fit(
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 943, in _run
    self.strategy.setup_environment()
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 153, in setup_environment
    super().setup_environment()
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 129, in setup_environment
    self.accelerator.setup_device(self.root_device)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/accelerators/cuda.py", line 46, in setup_device
    _check_cuda_matmul_precision(device)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/lightning_fabric/accelerators/cuda.py", line 361, in _check_cuda_matmul_precision
    if not torch.cuda.is_available() or not _is_ampere_or_later(device):
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/lightning_fabric/accelerators/cuda.py", line 355, in _is_ampere_or_later
    major, _ = torch.cuda.get_device_capability(device)
TypeError: cannot unpack non-iterable NoneType object
/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/torch_npu/npu/utils.py:88: UserWarning: torch.npu.get_device_capability isn't implemented!
  warnings.warn("torch.npu.get_device_capability isn't implemented!")
Traceback (most recent call last):
  File "/home/m00830934/code/Open-Sora-Plan/opensora/train/train_causalvae.py", line 108, in <module>
    train(args[0])
  File "/home/m00830934/code/Open-Sora-Plan/opensora/train/train_causalvae.py", line 97, in train
    trainer.fit(
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 943, in _run
    self.strategy.setup_environment()
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 153, in setup_environment
    super().setup_environment()
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 129, in setup_environment
    self.accelerator.setup_device(self.root_device)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/pytorch_lightning/accelerators/cuda.py", line 46, in setup_device
    _check_cuda_matmul_precision(device)
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/lightning_fabric/accelerators/cuda.py", line 361, in _check_cuda_matmul_precision
    if not torch.cuda.is_available() or not _is_ampere_or_later(device):
  File "/home/m00830934/anaconda3/envs/opensora-plan/lib/python3.8/site-packages/lightning_fabric/accelerators/cuda.py", line 355, in _is_ampere_or_later
    major, _ = torch.cuda.get_device_capability(device)
TypeError: cannot unpack non-iterable NoneType object

**Comment by LinB203** [comment]
抱歉回复迟了，我们目前正在积极适配训了diffusion的代码。下一版代码将会推出。
