### ISSUE TITLE
How to use the model from Stage 1 in Stage 2?

### ISSUE THREAD

**Issue by atomrun39** [PKU-YuanGroup/Open-Sora-Plan#313]
May I ask if Stage 2 is trained using the Stage 1 model, and Stage 3 is trained using the Stage 2 model? If so, how to load the model trained in the previous stage?
For example, the train_videoae_17x256x256.sh model I trained is as follows:
![企业微信截图_17183542969083](https://github.com/PKU-YuanGroup/Open-Sora-Plan/assets/69252333/463e1d3e-fdf8-4286-8e5d-7923850f0677)

In train_videoae_65x256x256.sh, --pretrained diffuse_pytorch_model. safetensors，will report an error: pickle UnpicklingError: invalid load key, '\xbb'
--pretrained  mp_rank_00_model_states.pt, an error will be reported:
Traceback (most recent call last):
File "opensora/train/train_t2v. py", line 838, in <module>
Main (args)
File "opensora/train/train_t2v. py", line 223, in main
Checkpoint=torch. load (args. pretrained, map_location='cpu ') ['model']
KeyError: 'model'

How to correctly use the model trained with 17x256x256.sh in the train_videoae_65x256x256.sh script
Also, how do I download t2v.pt? https://huggingface.co/maxin-cn/Latte/resolve/main/t2v.pt  The link no longer exists.
Looking forward to a reply. Thank you

**Comment by LinB203** [comment]
--pretrained diffusion_pytorch_model.safetensors, which under the `checkpoint-xx/model` folder.
You can download a more powerful pretrained weight from [here](https://huggingface.co/maxin-cn/Latte-1/blob/main/t2v_v20240523.pt)
