### ISSUE TITLE
NCCL Error 1: unhandled cuda error

### ISSUE THREAD

**Issue by ZXMMD** [PKU-YuanGroup/Open-Sora-Plan#386]
我尝试使用4✖️A100(40G)进行简单的训练。
运行：bash scripts/text_condition/gpu/train_t2v.sh
nvcc -V:
<img width="348" alt="image" src="https://github.com/user-attachments/assets/f7f88ccd-68cf-4c8b-b6f1-5ef09134775c">
deepspeed_zero2_config.yaml:
```yaml
compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
 deepspeed_config_file: scripts/accelerate_configs/zero2.json
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: 12345
main_training_function: main
num_machines: 1
num_processes: 4
# gpu_ids: 0
use_cpu: false
```

train_t2v.sh
```bash
# export WANDB_MODE="offline"
export CUDA_VISIBLE_DEVICES=0,1,2,3
export ENTITY="linbin"
export HF_DATASETS_OFFLINE=1 
export TRANSFORMERS_OFFLINE=1
export PDSH_RCMD_TYPE=ssh
# NCCL setting
export GLOO_SOCKET_IFNAME=eth1
export NCCL_SOCKET_IFNAME=eth1
export NCCL_IB_HCA=mlx5_10:1,mlx5_11:1,mlx5_12:1,mlx5_13:1
export NCCL_IB_GID_INDEX=3
export NCCL_IB_TC=162
export NCCL_IB_TIMEOUT=22
export NCCL_PXN_DISABLE=0
export NCCL_IB_QPS_PER_CONNECTION=4
export NCCL_ALGO=Ring
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1

# export NCCL_ALGO=Tree

accelerate launch \
    --config_file scripts/accelerate_configs/deepspeed_zero2_config.yaml \
    opensora/train/train_t2v_diffusers.py \
    --model OpenSoraT2V-ROPE-L/122 \
    --text_encoder_name DeepFloyd/t5-v1_1-xxl \
    --cache_dir "./cache_dir" \
    --dataset t2v \
    --data "scripts/train_data/merge_data.txt" \
    --ae CausalVAEModel_D4_4x8x8 \
    --ae_path "/data/myfile/Project/Open-Sora-Plan/Open-Sora-Plan-v1.2.0/vae" \
    --sample_rate 1 \
    --num_frames 29 \
    --max_height 256 \
    --max_width 256 \
    --interpolation_scale_t 1.0 \
    --interpolation_scale_h 1.0 \
    --interpolation_scale_w 1.0 \
    --attention_mode xformers \
    --gradient_checkpointing \
    --train_batch_size=1 \
    --dataloader_num_workers 4 \
    --gradient_accumulation_steps=1 \
    --max_train_steps=1000000 \
    --learning_rate=1e-4 \
    --lr_scheduler="constant" \
    --lr_warmup_steps=0 \
    --mixed_precision="bf16" \
    --report_to="wandb" \
    --checkpointing_steps=250 \
    --allow_tf32 \
    --model_max_length 512 \
    --use_image_num 0 \
    --tile_overlap_factor 0.125 \
    --snr_gamma 5.0 \
    --use_ema \
    --ema_start_step 0 \
    --cfg 0.1 \
    --noise_offset 0.02 \
    --use_rope \
    --ema_decay 0.999 \
    --enable_tiling \
    --speed_factor 1.0 \
    --group_frame \
    --sp_size 4 \
    --train_sp_batch_size 1 \
    --output_dir="bs16x8x1_29x480p_lr1e-4_snr5_ema999_opensora122_rope_mt5xxl_speed1.0" 
```

报错：
```python
Traceback (most recent call last):
  File "opensora/train/train_t2v_diffusers.py", line 957, in <module>
    main(args)
  File "opensora/train/train_t2v_diffusers.py", line 820, in main
    train_all_epoch()
  File "opensora/train/train_t2v_diffusers.py", line 794, in train_all_epoch
    if train_one_step(step, data_item, prof_):
  File "opensora/train/train_t2v_diffusers.py", line 761, in train_one_step
    x, cond, attn_mask, cond_mask, use_image_num = prepare_parallel_data(x, cond, attn_mask, cond_mask,
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 117, in prepare_parallel_data
    hidden_states, encoder_hidden_states, attention_mask, encoder_attention_mask = all_to_all(hidden_states,
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 105, in all_to_all
    hidden_states = _single_all_to_all(hidden_states, scatter_dim=2, gather_dim=0, enable_HCCL=True)
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 47, in _single_all_to_all
    dist.all_to_all_single(output, input_t, group=nccl_info.group)
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3532, in all_to_all_single
    work = group.alltoall_base(
RuntimeError: NCCL Error 1: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
```
似乎是GPU之间的通信有问题，请问您知道如何解决吗？

完整报错信息：
```python
08/13/2024 10:20:47 - INFO - __main__ -   Num examples = 40
08/13/2024 10:20:47 - INFO - __main__ -   Num Epochs = 100000
08/13/2024 10:20:47 - INFO - __main__ -   Instantaneous batch size per device = 1
08/13/2024 10:20:47 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 1
08/13/2024 10:20:47 - INFO - __main__ -   Gradient Accumulation steps = 1
08/13/2024 10:20:47 - INFO - __main__ -   Total optimization steps = 1000000
08/13/2024 10:20:47 - INFO - __main__ -   Total training parameters = 2.771907856 B
Steps:   0%|                                                                                                                                                                                         | 0/1000000 [00:00<?, ?it/s]
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO Using network Socket
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO Using network Socket
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO Using network Socket
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO Using network Socket
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO NVLS multicast support is not available on dev 0
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO NVLS multicast support is not available on dev 3
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO NVLS multicast support is not available on dev 1
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO NVLS multicast support is not available on dev 2
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO Trees [0] 2/-1/-1->1->0 [1] 2/-1/-1->1->0
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] 3/-1/-1->2->1
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO Channel 00/02 :    0   1   2   3
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] -1/-1/-1->3->2
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO P2P Chunksize set to 131072
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO P2P Chunksize set to 131072
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO Channel 01/02 :    0   1   2   3
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO P2P Chunksize set to 131072
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO P2P Chunksize set to 131072
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO Channel 00 : 2[1040] -> 3[1050] via SHM/direct/direct
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO Channel 01 : 2[1040] -> 3[1050] via SHM/direct/direct
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO Channel 00 : 0[1020] -> 1[1030] via SHM/direct/direct
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO Channel 00 : 1[1030] -> 2[1040] via SHM/direct/direct
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO Channel 00 : 3[1050] -> 0[1020] via SHM/direct/direct
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO Channel 01 : 0[1020] -> 1[1030] via SHM/direct/direct
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO Channel 01 : 1[1030] -> 2[1040] via SHM/direct/direct
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO Channel 01 : 3[1050] -> 0[1020] via SHM/direct/direct
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO Connected all rings
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO Connected all rings
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO Connected all rings
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO Connected all rings
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO Channel 00 : 3[1050] -> 2[1040] via SHM/direct/direct
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO Channel 01 : 3[1050] -> 2[1040] via SHM/direct/direct
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO Channel 00 : 2[1040] -> 1[1030] via SHM/direct/direct
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO Channel 01 : 2[1040] -> 1[1030] via SHM/direct/direct
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO Connected all trees
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO NCCL_ALGO set by environment to Ring
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO Channel 00 : 1[1030] -> 0[1020] via SHM/direct/direct
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO Channel 01 : 1[1030] -> 0[1020] via SHM/direct/direct
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO Connected all trees
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO NCCL_ALGO set by environment to Ring
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO Connected all trees
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO NCCL_ALGO set by environment to Ring
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO Connected all trees
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO NCCL_ALGO set by environment to Ring
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
ins-7df6eojsifuykig9:3018451:3023993 [0] NCCL INFO comm 0x7f8398e88e10 rank 0 nranks 4 cudaDev 0 busId 1020 commId 0x990e861bfffc9fad - Init COMPLETE
ins-7df6eojsifuykig9:3018453:3023995 [2] NCCL INFO comm 0x7fa744c08e00 rank 2 nranks 4 cudaDev 2 busId 1040 commId 0x990e861bfffc9fad - Init COMPLETE
ins-7df6eojsifuykig9:3018454:3023994 [3] NCCL INFO comm 0x7f4627f1ebc0 rank 3 nranks 4 cudaDev 3 busId 1050 commId 0x990e861bfffc9fad - Init COMPLETE
ins-7df6eojsifuykig9:3018452:3023996 [1] NCCL INFO comm 0x7f48db5bbff0 rank 1 nranks 4 cudaDev 1 busId 1030 commId 0x990e861bfffc9fad - Init COMPLETE
ins-7df6eojsifuykig9:3018452:3024012 [1] NCCL INFO Channel 00 : 1[1030] -> 2[1040] via SHM/direct/direct
ins-7df6eojsifuykig9:3018451:3024010 [0] NCCL INFO Channel 00 : 0[1020] -> 1[1030] via SHM/direct/direct
ins-7df6eojsifuykig9:3018452:3024012 [1] NCCL INFO Channel 01 : 1[1030] -> 2[1040] via SHM/direct/direct
ins-7df6eojsifuykig9:3018451:3024010 [0] NCCL INFO Channel 01 : 0[1020] -> 1[1030] via SHM/direct/direct
ins-7df6eojsifuykig9:3018454:3024009 [3] NCCL INFO Channel 00 : 3[1050] -> 0[1020] via SHM/direct/direct
ins-7df6eojsifuykig9:3018453:3024011 [2] NCCL INFO Channel 00 : 2[1040] -> 3[1050] via SHM/direct/direct
ins-7df6eojsifuykig9:3018453:3024011 [2] NCCL INFO Channel 01 : 2[1040] -> 3[1050] via SHM/direct/direct
ins-7df6eojsifuykig9:3018454:3024009 [3] NCCL INFO Channel 01 : 3[1050] -> 0[1020] via SHM/direct/direct
ins-7df6eojsifuykig9:3018452:3024012 [1] NCCL INFO Channel 00 : 1[1030] -> 3[1050] via SHM/direct/direct
ins-7df6eojsifuykig9:3018452:3024012 [1] NCCL INFO Channel 01 : 1[1030] -> 3[1050] via SHM/direct/direct
ins-7df6eojsifuykig9:3018453:3024011 [2] NCCL INFO Channel 00 : 2[1040] -> 0[1020] via SHM/direct/direct
ins-7df6eojsifuykig9:3018454:3024009 [3] NCCL INFO Channel 00 : 3[1050] -> 1[1030] via SHM/direct/direct
ins-7df6eojsifuykig9:3018453:3024011 [2] NCCL INFO Channel 01 : 2[1040] -> 0[1020] via SHM/direct/direct
ins-7df6eojsifuykig9:3018454:3024009 [3] NCCL INFO Channel 01 : 3[1050] -> 1[1030] via SHM/direct/direct
ins-7df6eojsifuykig9:3018451:3024010 [0] NCCL INFO Channel 00 : 0[1020] -> 2[1040] via SHM/direct/direct
ins-7df6eojsifuykig9:3018451:3024010 [0] NCCL INFO Channel 01 : 0[1020] -> 2[1040] via SHM/direct/direct
ins-7df6eojsifuykig9:3018454:3024009 [3] NCCL INFO Channel 00 : 3[1050] -> 2[1040] via SHM/direct/direct
ins-7df6eojsifuykig9:3018454:3024009 [3] NCCL INFO Channel 01 : 3[1050] -> 2[1040] via SHM/direct/direct
ins-7df6eojsifuykig9:3018452:3024012 [1] NCCL INFO Channel 00 : 1[1030] -> 0[1020] via SHM/direct/direct
ins-7df6eojsifuykig9:3018452:3024012 [1] NCCL INFO Channel 01 : 1[1030] -> 0[1020] via SHM/direct/direct
ins-7df6eojsifuykig9:3018451:3024010 [0] NCCL INFO Channel 00 : 0[1020] -> 3[1050] via SHM/direct/direct
ins-7df6eojsifuykig9:3018453:3024011 [2] NCCL INFO Channel 00 : 2[1040] -> 1[1030] via SHM/direct/direct
ins-7df6eojsifuykig9:3018451:3024010 [0] NCCL INFO Channel 01 : 0[1020] -> 3[1050] via SHM/direct/direct
ins-7df6eojsifuykig9:3018453:3024011 [2] NCCL INFO Channel 01 : 2[1040] -> 1[1030] via SHM/direct/direct

ins-7df6eojsifuykig9:3018451:3018451 [0] enqueue.cc:1085 NCCL WARN Cuda failure 'out of memory'
ins-7df6eojsifuykig9:3018451:3018451 [0] NCCL INFO group.cc:173 -> 1
ins-7df6eojsifuykig9:3018451:3018451 [0] NCCL INFO group.cc:341 -> 1
ins-7df6eojsifuykig9:3018451:3018451 [0] NCCL INFO group.cc:422 -> 1
ins-7df6eojsifuykig9:3018451:3018451 [0] NCCL INFO group.cc:106 -> 1

ins-7df6eojsifuykig9:3018452:3018452 [1] enqueue.cc:1085 NCCL WARN Cuda failure 'out of memory'
ins-7df6eojsifuykig9:3018452:3018452 [1] NCCL INFO group.cc:173 -> 1
ins-7df6eojsifuykig9:3018452:3018452 [1] NCCL INFO group.cc:341 -> 1
ins-7df6eojsifuykig9:3018452:3018452 [1] NCCL INFO group.cc:422 -> 1
ins-7df6eojsifuykig9:3018452:3018452 [1] NCCL INFO group.cc:106 -> 1

ins-7df6eojsifuykig9:3018454:3018454 [3] enqueue.cc:1085 NCCL WARN Cuda failure 'out of memory'
ins-7df6eojsifuykig9:3018454:3018454 [3] NCCL INFO group.cc:173 -> 1
ins-7df6eojsifuykig9:3018454:3018454 [3] NCCL INFO group.cc:341 -> 1
ins-7df6eojsifuykig9:3018454:3018454 [3] NCCL INFO group.cc:422 -> 1
ins-7df6eojsifuykig9:3018454:3018454 [3] NCCL INFO group.cc:106 -> 1

ins-7df6eojsifuykig9:3018453:3018453 [2] enqueue.cc:1085 NCCL WARN Cuda failure 'out of memory'
ins-7df6eojsifuykig9:3018453:3018453 [2] NCCL INFO group.cc:173 -> 1
ins-7df6eojsifuykig9:3018453:3018453 [2] NCCL INFO group.cc:341 -> 1
ins-7df6eojsifuykig9:3018453:3018453 [2] NCCL INFO group.cc:422 -> 1
ins-7df6eojsifuykig9:3018453:3018453 [2] NCCL INFO group.cc:106 -> 1
Traceback (most recent call last):
  File "opensora/train/train_t2v_diffusers.py", line 957, in <module>
    main(args)
  File "opensora/train/train_t2v_diffusers.py", line 820, in main
    train_all_epoch()
  File "opensora/train/train_t2v_diffusers.py", line 794, in train_all_epoch
    if train_one_step(step, data_item, prof_):
  File "opensora/train/train_t2v_diffusers.py", line 761, in train_one_step
    x, cond, attn_mask, cond_mask, use_image_num = prepare_parallel_data(x, cond, attn_mask, cond_mask,
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 117, in prepare_parallel_data
    hidden_states, encoder_hidden_states, attention_mask, encoder_attention_mask = all_to_all(hidden_states,
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 105, in all_to_all
    hidden_states = _single_all_to_all(hidden_states, scatter_dim=2, gather_dim=0, enable_HCCL=True)
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 47, in _single_all_to_all
    dist.all_to_all_single(output, input_t, group=nccl_info.group)
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3532, in all_to_all_single
    work = group.alltoall_base(
RuntimeError: NCCL Error 1: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
Traceback (most recent call last):
  File "opensora/train/train_t2v_diffusers.py", line 957, in <module>
    main(args)
  File "opensora/train/train_t2v_diffusers.py", line 820, in main
    train_all_epoch()
  File "opensora/train/train_t2v_diffusers.py", line 794, in train_all_epoch
    if train_one_step(step, data_item, prof_):
  File "opensora/train/train_t2v_diffusers.py", line 761, in train_one_step
    x, cond, attn_mask, cond_mask, use_image_num = prepare_parallel_data(x, cond, attn_mask, cond_mask,
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 117, in prepare_parallel_data
    hidden_states, encoder_hidden_states, attention_mask, encoder_attention_mask = all_to_all(hidden_states,
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 105, in all_to_all
    hidden_states = _single_all_to_all(hidden_states, scatter_dim=2, gather_dim=0, enable_HCCL=True)
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 47, in _single_all_to_all
    dist.all_to_all_single(output, input_t, group=nccl_info.group)
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3532, in all_to_all_single
    work = group.alltoall_base(
RuntimeError: NCCL Error 1: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
Traceback (most recent call last):
  File "opensora/train/train_t2v_diffusers.py", line 957, in <module>
    main(args)
  File "opensora/train/train_t2v_diffusers.py", line 820, in main
    train_all_epoch()
  File "opensora/train/train_t2v_diffusers.py", line 794, in train_all_epoch
    if train_one_step(step, data_item, prof_):
  File "opensora/train/train_t2v_diffusers.py", line 761, in train_one_step
    x, cond, attn_mask, cond_mask, use_image_num = prepare_parallel_data(x, cond, attn_mask, cond_mask,
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 117, in prepare_parallel_data
    hidden_states, encoder_hidden_states, attention_mask, encoder_attention_mask = all_to_all(hidden_states,
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 105, in all_to_all
    hidden_states = _single_all_to_all(hidden_states, scatter_dim=2, gather_dim=0, enable_HCCL=True)
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 47, in _single_all_to_all
    dist.all_to_all_single(output, input_t, group=nccl_info.group)
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3532, in all_to_all_single
    work = group.alltoall_base(
RuntimeError: NCCL Error 1: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
Traceback (most recent call last):
  File "opensora/train/train_t2v_diffusers.py", line 957, in <module>
    main(args)
  File "opensora/train/train_t2v_diffusers.py", line 820, in main
    train_all_epoch()
  File "opensora/train/train_t2v_diffusers.py", line 794, in train_all_epoch
    if train_one_step(step, data_item, prof_):
  File "opensora/train/train_t2v_diffusers.py", line 761, in train_one_step
    x, cond, attn_mask, cond_mask, use_image_num = prepare_parallel_data(x, cond, attn_mask, cond_mask,
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 117, in prepare_parallel_data
    hidden_states, encoder_hidden_states, attention_mask, encoder_attention_mask = all_to_all(hidden_states,
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 105, in all_to_all
    hidden_states = _single_all_to_all(hidden_states, scatter_dim=2, gather_dim=0, enable_HCCL=True)
  File "/data/myfile/Project/Open-Sora-Plan/opensora/utils/communications.py", line 47, in _single_all_to_all
    dist.all_to_all_single(output, input_t, group=nccl_info.group)
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3532, in all_to_all_single
    work = group.alltoall_base(
RuntimeError: NCCL Error 1: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /data/myfile/Project/Open-Sora-Plan/wandb/offline-run-20240813_102044-py0k6ocw
wandb: Find logs at: ./wandb/offline-run-20240813_102044-py0k6ocw/logs
ins-7df6eojsifuykig9:3018452:3023997 [1] NCCL INFO [Service thread] Connection closed by localRank 1
ins-7df6eojsifuykig9:3018452:3018452 [1] NCCL INFO comm 0x7f48db5bbff0 rank 1 nranks 4 cudaDev 1 busId 1030 - Abort COMPLETE
ins-7df6eojsifuykig9:3018453:3023998 [2] NCCL INFO [Service thread] Connection closed by localRank 2
ins-7df6eojsifuykig9:3018453:3018453 [2] NCCL INFO comm 0x7fa744c08e00 rank 2 nranks 4 cudaDev 2 busId 1040 - Abort COMPLETE
ins-7df6eojsifuykig9:3018454:3024000 [3] NCCL INFO [Service thread] Connection closed by localRank 3
ins-7df6eojsifuykig9:3018454:3018454 [3] NCCL INFO comm 0x7f4627f1ebc0 rank 3 nranks 4 cudaDev 3 busId 1050 - Abort COMPLETE
[2024-08-13 10:20:54,386] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 3018451 closing signal SIGTERM
[2024-08-13 10:20:55,152] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 3018452) of binary: /data/conda/envs/opensoraplan/bin/python
Traceback (most recent call last):
  File "/data/conda/envs/opensoraplan/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1060, in launch_command
    deepspeed_launcher(args)
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/accelerate/commands/launch.py", line 764, in deepspeed_launcher
    distrib_run.run(args)
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/conda/envs/opensoraplan/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
opensora/train/train_t2v_diffusers.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-13_10:20:54
  host      : ins-7df6eojsifuykig9
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3018453)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-13_10:20:54
  host      : ins-7df6eojsifuykig9
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 3018454)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-13_10:20:54
  host      : ins-7df6eojsifuykig9
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3018452)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by ZXMMD** [comment]
另外想问一下，支持4✖️A100(40G)进行训练吗？感谢！

**Comment by LinB203** [comment]
他应当是支持的，你可以先试试低分辨率帧数的非sp训练，看看是否会报错。先排除是否是sp的问题。同时也可以试一下ddp的推理脚本。

**Comment by ZXMMD** [comment]
好的，谢谢回复！
