### ISSUE TITLE
[BUG] PyTorch 2.4.0 rocm 6.1| ... cannot import name 'LORA_ATTENTION_PROCESSORS' from 'diffusers.models.attention_processor'

### ISSUE THREAD

**Issue by unclemusclez** [PKU-YuanGroup/Open-Sora-Plan#401]
```bash
Torch version: 2.4.0+rocm6.1
PyTorch version 2.4.0+rocm6.1 available.
Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead
Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead
Traceback (most recent call last):
  File "/home/musclez/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/musclez/ComfyUI/custom_nodes/ComfyUI-Open-Sora-Plan/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "/home/musclez/ComfyUI/custom_nodes/ComfyUI-Open-Sora-Plan/nodes.py", line 29, in <module>
    from opensora.models.diffusion.latte.modeling_latte import LatteT2V
  File "/home/musclez/ComfyUI/custom_nodes/ComfyUI-Open-Sora-Plan/opensora/models/diffusion/__init__.py", line 2, in <module>
    from .latte.modeling_latte import Latte_models
  File "/home/musclez/ComfyUI/custom_nodes/ComfyUI-Open-Sora-Plan/opensora/models/diffusion/latte/modeling_latte.py", line 21, in <module>
    from opensora.models.diffusion.latte.modules import PatchEmbed, BasicTransformerBlock, BasicTransformerBlock_, AdaLayerNormSingle, \
  File "/home/musclez/ComfyUI/custom_nodes/ComfyUI-Open-Sora-Plan/opensora/models/diffusion/latte/modules.py", line 14, in <module>
    from diffusers.models.attention_processor import SpatialNorm, LORA_ATTENTION_PROCESSORS, \
ImportError: cannot import name 'LORA_ATTENTION_PROCESSORS' from 'diffusers.models.attention_processor' (/home/musclez/ComfyUI/.venv/lib/python3.11/site-packages/diffusers/models/attention_processor.py)

Cannot import /home/musclez/ComfyUI/custom_nodes/ComfyUI-Open-Sora-Plan module for custom nodes: cannot import name 'LORA_ATTENTION_PROCESSORS' from 'diffusers.models.attention_processor' (/home/musclez/ComfyUI/.venv/lib/python3.11/site-packages/diffusers/models/attention_processor.py)
```

**Comment by unclemusclez** [comment]
this is due to using a later version of `diffusers` and LORA_ATTENTION_PROCESSORS has been deprecated in 2.26.0.
