### ISSUE TITLE
Issues with Fine-Tuning Model

### ISSUE THREAD

**Issue by yachty66** [PKU-YuanGroup/Open-Sora-Plan#499]
Hello,

I am trying to fine-tune the model, but I have run into a number of issues today.

Before making a longer training run with more data, I want to conduct a smaller training run with a small dummy dataset to see if and how the training works. The videos for the dummy dataset I created are in the following GitHub repo: [Dummy Dataset Repository](https://github.com/yachty66/open_sora_plan_dummy_data).

The script I am using for my test training is here: [Training Script](https://github.com/yachty66/open_sora_plan_dummy_data/blob/main/train_t2v_v1_3.sh).

Inside the `define_frame_index` function from [t2v_datasets.py](https://github.com/yachty66/open_sora_plan_dummy_data/blob/main/t2v_datasets.py), I commented out a few lines of code that run checks on the video. I did this to prevent errors that would otherwise occur. 

When running the training script, I get the following error:

```
10/23/2024 20:48:13 - INFO - __main__ -   Num examples = 10
10/23/2024 20:48:13 - INFO - __main__ -   Num Epochs = 10
10/23/2024 20:48:13 - INFO - __main__ -   Instantaneous batch size per device = 1
10/23/2024 20:48:13 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 1
10/23/2024 20:48:13 - INFO - __main__ -   Gradient Accumulation steps = 1
10/23/2024 20:48:13 - INFO - __main__ -   Total optimization steps = 100
10/23/2024 20:48:13 - INFO - __main__ -   Total optimization steps (num_update_steps_per_epoch) = 10
10/23/2024 20:48:13 - INFO - __main__ -   Total training parameters = 2.7719816 B
10/23/2024 20:48:13 - INFO - __main__ -   AutoEncoder = WFVAEModel_D8_4x8x8; Dtype = torch.bfloat16; Parameters = 0.147347724 B
10/23/2024 20:48:13 - INFO - __main__ -   Text_enc_1 = models/text_encoder; Dtype = torch.bfloat16; Parameters = 5.65517312 B
Checkpoint 'latest' does not exist. Starting a new training run.
Steps:   0%|                                                                                                                            | 0/100 [00:00<?, ?it/s]Skip the data of 0 step!
Video training/videos/video_4.mp4 is too short to encode. Using available frames.
Video training/videos/video_6.mp4 is too short to encode. Using available frames.
Video training/videos/video_9.mp4 is too short to encode. Using available frames.
Video training/videos/video_8.mp4 is too short to encode. Using available frames.
Video training/videos/video_5.mp4 is too short to encode. Using available frames.
Video training/videos/video_2.mp4 is too short to encode. Using available frames.
Video training/videos/video_10.mp4 is too short to encode. Using available frames.
Video training/videos/video_7.mp4 is too short to encode. Using available frames.
Video training/videos/video_3.mp4 is too short to encode. Using available frames.
Video training/videos/video_1.mp4 is too short to encode. Using available frames.
Traceback (most recent call last):
  File "/workspace/Open-Sora-Plan/opensora/train/train_t2v_diffusers.py", line 1154, in <module>
    main(args)
  File "/workspace/Open-Sora-Plan/opensora/train/train_t2v_diffusers.py", line 1002, in main
    train_one_epoch()
  File "/workspace/Open-Sora-Plan/opensora/train/train_t2v_diffusers.py", line 958, in train_one_epoch
    if train_one_step(step, data_item, prof_):
  File "/workspace/Open-Sora-Plan/opensora/train/train_t2v_diffusers.py", line 942, in train_one_step
    run(step_, x, model_kwargs, prof_)
  File "/workspace/Open-Sora-Plan/opensora/train/train_t2v_diffusers.py", line 682, in run
    timesteps = explicit_uniform_sampling(
  File "/workspace/Open-Sora-Plan/opensora/utils/utils.py", line 67, in explicit_uniform_sampling
    sampled_timesteps = torch.LongTensor([round(random.uniform(lower_bound, upper_bound)) for _ in range(bsz)], device=device)
RuntimeError: legacy constructor expects device type: cpu but device type: cuda was passed
Traceback (most recent call last):
  File "/workspace/Open-Sora-Plan/opensora/train/train_t2v_diffusers.py", line 1154, in <module>
    main(args)
  File "/workspace/Open-Sora-Plan/opensora/train/train_t2v_diffusers.py", line 1002, in main
    train_one_epoch()
  File "/workspace/Open-Sora-Plan/opensora/train/train_t2v_diffusers.py", line 958, in train_one_epoch
    if train_one_step(step, data_item, prof_):
  File "/workspace/Open-Sora-Plan/opensora/train/train_t2v_diffusers.py", line 942, in train_one_step
    run(step_, x, model_kwargs, prof_)
  File "/workspace/Open-Sora-Plan/opensora/train/train_t2v_diffusers.py", line 682, in run
    timesteps = explicit_uniform_sampling(
  File "/workspace/Open-Sora-Plan/opensora/utils/utils.py", line 67, in explicit_uniform_sampling
    sampled_timesteps = torch.LongTensor([round(random.uniform(lower_bound, upper_bound)) for _ in range(bsz)], device=device)
RuntimeError: legacy constructor expects device type: cpu but device type: cuda was passed
```

My environment consists of:
- **PyTorch version**: 2.1.0
- **CUDA**: 11.8.0
- **OS**: Ubuntu 22.04
- **GPU**: A100 80GB SXM

### Questions:
How can I avoid the error?

Thank you for your help!

**Comment by LinB203** [comment]
Hi, we are fixed this bug, sorry for that. You can see  the main branch to avoid this error.
https://github.com/PKU-YuanGroup/Open-Sora-Plan/commit/390de3f77751f73f139a53c90875a5b0a740535f

**Comment by yachty66** [comment]
Thank you! I will try it out today and report if it works!

**Comment by yachty66** [comment]
Worked. Closing the issue. Thank you.
