### ISSUE TITLE
AttributeError: 'OpenSoraT2V_v1_3' object has no attribute 'pos_embed_mask'

### ISSUE THREAD

**Issue by WangRongsheng** [PKU-YuanGroup/Open-Sora-Plan#540]
```python
CUDA_VISIBLE_DEVICES=0 torchrun --nnodes=1 --nproc_per_node 1 --master_port 29514 \
    -m opensora.sample.sample \
    --model_path "/root/autodl-tmp/Open-Sora-Plan-1.3.1/Open-Sora-Plan-v1.3.0/any93x640x640_i2v" \
    --version v1_3 \
    --num_frames 93 \
    --height 640 \
    --width 640 \
    --cache_dir "../cache_dir" \
    --text_encoder_name_1 "/root/autodl-tmp/Open-Sora-Plan-1.3.1/model/hub/models--hf-models--mt5-xxl/snapshots/e07c395916dfbc315d4e5e48b4a54a1e8821b5c0" \
    --text_prompt "examples/medsora_prompt_output.txt" \
    --ae WFVAEModel_D8_4x8x8 \
    --ae_path "/root/autodl-tmp/Open-Sora-Plan-1.3.1/Open-Sora-Plan-v1.3.0/vae" \
    --save_img_path "./train_1_3_nomotion_fps18" \
    --fps 18 \
    --guidance_scale 7.5 \
    --num_sampling_steps 100 \
    --max_sequence_length 512 \
    --sample_method EulerAncestralDiscrete \
    --seed 42 \
    --num_samples_per_prompt 1 \
    --rescale_betas_zero_snr \
    --prediction_type "v_prediction" 
```

报错：
```
/root/miniconda3/lib/python3.10/site-packages/diffusers/configuration_utils.py:245: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a model, please use <class 'opensora.models.causalvideovae.model.vae.modeling_wfvae.WFVAEModel'>.load_config(...) followed by <class 'opensora.models.causalvideovae.model.vae.modeling_wfvae.WFVAEModel'>.from_config(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)
init from /root/autodl-tmp/Open-Sora-Plan-1.3.1/Open-Sora-Plan-v1.3.0/vae/merged.ckpt
Load from ema model!
['encoder.wavelet_tranform_l1.aa', 'encoder.wavelet_tranform_l1.ad', 'encoder.wavelet_tranform_l1.da', 'encoder.wavelet_tranform_l1.dd', 'encoder.wavelet_tranform_l2.h_conv.conv.weight', 'encoder.wavelet_tranform_l2.g_conv.conv.weight', 'encoder.wavelet_tranform_l2.hh_conv.conv.weight', 'encoder.wavelet_tranform_l2.gh_conv.conv.weight', 'encoder.wavelet_tranform_l2.h_v_conv.conv.weight', 'encoder.wavelet_tranform_l2.g_v_conv.conv.weight', 'encoder.wavelet_tranform_l2.hh_v_conv.conv.weight', 'encoder.wavelet_tranform_l2.gh_v_conv.conv.weight', 'decoder.inverse_wavelet_tranform_l1.aa', 'decoder.inverse_wavelet_tranform_l1.ad', 'decoder.inverse_wavelet_tranform_l1.da', 'decoder.inverse_wavelet_tranform_l1.dd', 'decoder.inverse_wavelet_tranform_l2.h', 'decoder.inverse_wavelet_tranform_l2.g', 'decoder.inverse_wavelet_tranform_l2.hh', 'decoder.inverse_wavelet_tranform_l2.gh', 'decoder.inverse_wavelet_tranform_l2.h_v', 'decoder.inverse_wavelet_tranform_l2.g_v', 'decoder.inverse_wavelet_tranform_l2.hh_v', 'decoder.inverse_wavelet_tranform_l2.gh_v'] []
/root/miniconda3/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
/root/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
/root/miniconda3/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py:551: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
The config attributes {'vae_scale_factor_t': 4} were passed to OpenSoraT2V_v1_3, but are not expected and will be ignored. Please verify your config.json configuration file.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/autodl-tmp/Open-Sora-Plan-1.3.1/opensora/sample/sample.py", line 33, in <module>
    pipeline = prepare_pipeline(args, dtype, device)
  File "/root/autodl-tmp/Open-Sora-Plan-1.3.1/opensora/utils/sample_utils.py", line 124, in prepare_pipeline
    transformer_model = OpenSoraT2V_v1_3.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 817, in from_pretrained
    raise e
  File "/root/miniconda3/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 774, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/big_modeling.py", line 613, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1878, in load_checkpoint_in_model
    set_module_tensor_to_device(
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 334, in set_module_tensor_to_device
    new_module = getattr(module, split)
  File "/root/miniconda3/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 151, in __getattr__
    return super().__getattr__(name)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'OpenSoraT2V_v1_3' object has no attribute 'pos_embed_mask'
```

**Comment by yunyangge** [comment]
Please check if the script you are using is `sample_inpaint_v1_3.sh`. It seems that your script might be using the T2V version.

**Comment by WangRongsheng** [comment]
yes, it is `T2V`. if i use `sample_inpaint_v1_3.sh`, how can i set `--conditional_pixel_values_path`?

https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/scripts/text_condition/gpu/sample_inpaint_v1_3.sh#L15C3-L15C65

**Comment by yunyangge** [comment]
Please check our guide: https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/docs/I2V.md, which may help you solve this problem.

**Comment by WangRongsheng** [comment]
solved!
