### ISSUE TITLE
求助：各种模型都下好了怎么用npu进行推理呢？按照readme操作了好久报错了。

### ISSUE THREAD

**Issue by sguo112** [PKU-YuanGroup/Open-Sora-Plan#551]
<img width="894" alt="从" src="https://github.com/user-attachments/assets/5cf21f36-dec3-4089-b29d-10a46109ab91">
使用的是910b

求助执行bash scripts/text_condition/npu/sample_t2v_v1_3.sh报错如上图

脚本配置修改如下
--model_path "//Open-Sora-Plan/Open-Sora-Plan-v1.3.0/any93x640x640" \
--ae WFVAEModel_D8_4x8x8 --ae_path "Open-Sora-Plan/Open-Sora-Plan-v1.3.0/vae" \
--text_encoder_name_1 "/Open-Sora-Plan/mt5" --rescale_betas_zero_snr

**Comment by yunyangge** [comment]
这是npu报的warning，是正常情况，你有报error吗？
This is a warning reported by NPU, which is a normal situation. Did you report an error?

**Comment by sguo112** [comment]
> 这是npu报的warning，是正常情况，你有报error吗？ This is a warning reported by NPU, which is a normal situation. Did you report an error?

有的
The following error is reported：
```
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/root/anaconda3/envs/deepspeed/lib/python3.10/site-packages/huggingface_hub/__init__.py)
[ERROR] 2024-12-04-19:08:02 (PID:3663810, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
/root/anaconda3/envs/deepspeed/lib/python3.10/tempfile.py:869: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpga4jvq_c'>
  _warnings.warn(warn_message, ResourceWarning)
E1204 19:08:04.672000 281473368985632 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 3663810) of binary: /root/anaconda3/envs/deepspeed/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/deepspeed/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/deepspeed/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/deepspeed/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/root/anaconda3/envs/deepspeed/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/root/anaconda3/envs/deepspeed/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/deepspeed/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
opensora.sample.sample FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-04_19:08:04
  host      : devserver-314b-0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3663810)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```
另外我想问下如何完整下载opensora 1 .3.0所需要的包，我在另一个环境下运行推理脚本总会提示缺少东西
In addition, I would like to ask how to fully download the package required for opensora 1.3.0, when I run inference scripts in another environment, it always indicates that something is missing
<img width="620" alt="捕获123123" src="https://github.com/user-attachments/assets/b69a0d6f-0d1f-43e3-9c9e-868147cbc673">
